### ISSUE TITLE
Fedora rawhide images for ppc64le are not updated

### ISSUE THREAD

**Issue by seth-priya** [fedora-cloud/docker-brew-fedora#76]
Hi All,

It seems that the latest rawhide images for Fedora (rawhide) at https://hub.docker.com/_/fedora?tab=tags do not have full multi-arch support? The manifest entry for ppc64le is missing (though I see that the ppc64le dockerfile in the repository was updated 13 days back).

and a pull fails with
docker pull fedora:rawhide
rawhide: Pulling from library/fedora
no matching manifest for linux/ppc64le in the manifest list entries

The below does work
docker pull ppc64le/fedora:rawhide
however that image has not been updated in a few months.

any specific reason for excluding the Power images?

Thanks,
Priya

**Comment by michelmno** [comment]
Does not seems to be a build problem as images available on fedora compose server, eg: https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20200913.n.0/compose/Container/ppc64le/images/

@sharkcz  do you have an idea on the subject ?

**Comment by jcajka** [comment]
@michelmno Hello, rawhide seems to build and it is not pushed for some reason. https://koji.fedoraproject.org/koji/buildinfo?buildID=1609978.
Looking also at the f33 https://koji.fedoraproject.org/koji/buildinfo?buildID=1610034 it seems that the ppc64le build fails somewhere in the anaconda https://koji.fedoraproject.org/koji/taskinfo?taskID=51360887. Also bit surprising is that although s390x is built successfully it is not pushed as the aarch64 image(maybe it is because it failed previously and we are in the freeze and there are no pushes atm?) Asking around atm.
@seth-priya Could you try to use directly the fedora registry via ```registry.fedoraproject.org/fedora:rawhide``` . The image is properly manifest listed.
See https://registry.fedoraproject.org/repo/fedora/tags/.

**Comment by seth-priya** [comment]
@michelmno , @jcajka thanks for looking into this. Yes, just validated and registry.fedoraproject.org/fedora:rawhide works well for me, thanks for the pointer. But, I do believe that it would be awesome if we can resolve the issue seen with pushing the image to DockerHub, as otherwise other images, build scripts and CI jobs referencing the dockerhub version directly would break on ppc64le :(  … I will try to check the logs in more detail as well, thanks

**Comment by jcajka** [comment]
@seth-priya happy to hear it works, registry.fp.o is really more workaround. It is good if we can be seen on the dockerhub. I plan to investigate the issue more. CC'ing @cverna and @siddharthvipul from infra.

**Comment by jcajka** [comment]
@seth-priya there should be push soon hopefully. @cverna and infra should be working on it. Build failures seems to have some sort of intermittent problem, still trying to make sense of it.

**Comment by seth-priya** [comment]
thanks @jcajka

**Comment by cverna** [comment]
@siddharthvipul are planning to do a release this week ? Otherwise I can run one

**Comment by asellappen** [comment]
Has this been fixed ? , I am facing the same issue on power on arch while pulling docker image for fedora:rawhide .

**Comment by cverna** [comment]
This is not yet fixed we have a problem with the build system and the images for pcc64le and s390x are failing to build

**Comment by jcajka** [comment]
@cverna Do you have link to the failing ppc64le builds? 
Latest builds that I see seem ok to me. Just checked with @sharkcz and  s390x should be failing due to this, https://pagure.io/releng/issue/9777,  missing mount point. 
IMHO partial pushes are better than non, but not sure if that is in violation of some Fedora policy.

**Comment by cverna** [comment]
So yeah between my morning and my evening ppc64le was fixed https://koji.fedoraproject.org/koji/taskinfo?taskID=52508269 and I think s390x should be fixed now so let's wait for tonight's build to happen and we should be able to push a complete set of image tomorrow :fireworks:

**Comment by siddharthvipul** [comment]
Just opened a PR to sync latest images: https://github.com/docker-library/official-images/pull/8812

**Comment by jcajka** [comment]
@siddharthvipul thank you

**Comment by jcajka** [comment]
@siddharthvipul @cverna thanks again the images seems to be there for the ppc64le, both rawhide and (f)33.

**Comment by seth-priya** [comment]
thanks @siddharthvipul @cverna @jcajka @michelmno for you help in getting the ppc64le images updated , this is really helpful :)

**Comment by cverna** [comment]
New PR opened that brings back s390x and arm32v7 https://github.com/docker-library/official-images/pull/8860.

Going to close that issue
